toastPrompts = [ "协议", "隐私政策", "隐私", "政策", "法律", "政策", "用户协议", "阅读", "同意", "确定",]

[privacyPolicyPrompts]
direct = [ "隐私权政策", "隐私政策", "隐私条款", "隐私协议", "隐私设置", "服务协议", "用户协议", "注册声明", "注册协议", "隐私", "政策", "条款", "协议",]
indirect = [ "同意", "授权", "允许", "关于", "设置", "我的", "个人", "我",]
