localChrome = "/home/ciscn/Ciscn/PoliGuard/src/dynamic/drivers/111"
appName = "小龙象"
appID = "wx7e3c3f665cd8e4e6"

[capabilities]
deviceName = "192.168.137.152:5555"
platformName = "Android"
appPackage = "com.tencent.mm"
appActivity = "com.tencent.mm.ui.LauncherUI"
automationName = "uiautomator2"
noReset = true
unicodeKeyboard = true
resetKeyboard = true
chromedriverExecutable = "/home/ciscn/Ciscn/PoliGuard/src/dynamic/drivers/107"
